# Site settings
title:          amodsachintha
description:    "tech stuff"
url:            "https://amodsachintha.github.io/"

# Author
author:
  name:         Amod Sachintha
  url:          amodsachintha.github.io
  email:        amod077@gmail.com

#social
facebook_username: amodsachintha
github_username: amodsachintha

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

jekyll_admin:
#  hidden_links:
#    - posts
#    - pages
#    - staticfiles
#    - datafiles
#    - configuration
